import type { 
  Stagiaire, 
  Tuteur, 
  RH, 
  Admin, 
  Candidature, 
  Convention, 
  TacheOnboarding, 
  Evaluation, 
  Notification,
  User,
  CandidatureExterne,
  DemandePartenariat,
  Universite,
  Ecole
} from './types'

// Users
export const mockStagiaires: Stagiaire[] = [
  {
    id: 'stg-1',
    email: 'marie.dupont@edu.fr',
    role: 'stagiaire',
    nom: 'Dupont',
    prenom: 'Marie',
    ecole: 'ENSEIRB-MATMECA',
    specialite: 'Informatique',
    telephone: '06 12 34 56 78',
    tuteurId: 'tut-1',
    universitId: 'univ-1',
    createdAt: '2024-01-15',
  },
  {
    id: 'stg-2',
    email: 'jean.martin@edu.fr',
    role: 'stagiaire',
    nom: 'Martin',
    prenom: 'Jean',
    ecole: 'Université de Bordeaux',
    specialite: 'Marketing',
    telephone: '06 98 76 54 32',
    tuteurId: 'tut-2',
    universitId: 'univ-1',
    createdAt: '2024-01-20',
  },
  {
    id: 'stg-3',
    email: 'sophie.bernard@edu.fr',
    role: 'stagiaire',
    nom: 'Bernard',
    prenom: 'Sophie',
    ecole: 'Sciences Po Bordeaux',
    specialite: 'Communication',
    telephone: '06 11 22 33 44',
    universitId: 'univ-1',
    createdAt: '2024-02-01',
  },
  // ESPRIT - 13 stagiaires
  {
    id: 'stg-esprit-1',
    email: 'amira.ben@esprit.tn',
    role: 'stagiaire',
    nom: 'Ben Amor',
    prenom: 'Amira',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Génie Logiciel',
    telephone: '21 621 234 567',
    tuteurId: 'tut-1',
    universitId: 'univ-2',
    createdAt: '2024-01-10',
  },
  {
    id: 'stg-esprit-2',
    email: 'ahmed.khlifi@esprit.tn',
    role: 'stagiaire',
    nom: 'Khlifi',
    prenom: 'Ahmed',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Réseaux',
    telephone: '21 621 345 678',
    tuteurId: 'tut-2',
    universitId: 'univ-2',
    createdAt: '2024-01-12',
  },
  {
    id: 'stg-esprit-3',
    email: 'yasmin.salem@esprit.tn',
    role: 'stagiaire',
    nom: 'Salem',
    prenom: 'Yasmin',
    ecole: 'ESPRIT',
    specialite: 'Informatique - IA et Data Science',
    telephone: '21 621 456 789',
    universitId: 'univ-2',
    createdAt: '2024-01-14',
  },
  {
    id: 'stg-esprit-4',
    email: 'karim.oueslati@esprit.tn',
    role: 'stagiaire',
    nom: 'Oueslati',
    prenom: 'Karim',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Sécurité',
    telephone: '21 621 567 890',
    tuteurId: 'tut-1',
    universitId: 'univ-2',
    createdAt: '2024-01-16',
  },
  {
    id: 'stg-esprit-5',
    email: 'nadia.triki@esprit.tn',
    role: 'stagiaire',
    nom: 'Triki',
    prenom: 'Nadia',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Web Développement',
    telephone: '21 621 678 901',
    universitId: 'univ-2',
    createdAt: '2024-01-18',
  },
  {
    id: 'stg-esprit-6',
    email: 'hamza.makhlouf@esprit.tn',
    role: 'stagiaire',
    nom: 'Makhlouf',
    prenom: 'Hamza',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Cloud Computing',
    telephone: '21 621 789 012',
    tuteurId: 'tut-2',
    universitId: 'univ-2',
    createdAt: '2024-01-20',
  },
  {
    id: 'stg-esprit-7',
    email: 'layla.gharsallah@esprit.tn',
    role: 'stagiaire',
    nom: 'Gharsallah',
    prenom: 'Layla',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Génie Logiciel',
    telephone: '21 621 890 123',
    universitId: 'univ-2',
    createdAt: '2024-01-22',
  },
  {
    id: 'stg-esprit-8',
    email: 'omar.berrada@esprit.tn',
    role: 'stagiaire',
    nom: 'Berrada',
    prenom: 'Omar',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Génie Logiciel',
    telephone: '21 621 901 234',
    tuteurId: 'tut-1',
    universitId: 'univ-2',
    createdAt: '2024-01-24',
  },
  {
    id: 'stg-esprit-9',
    email: 'rima.jebali@esprit.tn',
    role: 'stagiaire',
    nom: 'Jebali',
    prenom: 'Rima',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Réseaux',
    telephone: '21 622 012 345',
    universitId: 'univ-2',
    createdAt: '2024-01-26',
  },
  {
    id: 'stg-esprit-10',
    email: 'bilel.mansouri@esprit.tn',
    role: 'stagiaire',
    nom: 'Mansouri',
    prenom: 'Bilel',
    ecole: 'ESPRIT',
    specialite: 'Informatique - IA et Data Science',
    telephone: '21 622 123 456',
    tuteurId: 'tut-2',
    universitId: 'univ-2',
    createdAt: '2024-01-28',
  },
  {
    id: 'stg-esprit-11',
    email: 'hana.wafi@esprit.tn',
    role: 'stagiaire',
    nom: 'Wafi',
    prenom: 'Hana',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Web Développement',
    telephone: '21 622 234 567',
    universitId: 'univ-2',
    createdAt: '2024-02-01',
  },
  {
    id: 'stg-esprit-12',
    email: 'samir.zouari@esprit.tn',
    role: 'stagiaire',
    nom: 'Zouari',
    prenom: 'Samir',
    ecole: 'ESPRIT',
    specialite: 'Informatique - Cloud Computing',
    telephone: '21 622 345 678',
    tuteurId: 'tut-1',
    universitId: 'univ-2',
    createdAt: '2024-02-03',
  },
  {
    id: 'stg-ecole-1',
    email: 'thomas.bernard@lycee.fr',
    role: 'stagiaire',
    nom: 'Bernard',
    prenom: 'Thomas',
    ecole: 'Lycée Victor Duruy',
    specialite: 'Terminale - Spécialité NSI',
    telephone: '06 45 67 89 01',
    ecoleId: 'ecole-1',
    createdAt: '2024-02-10',
  },
  {
    id: 'stg-ecole-2',
    email: 'camille.dubois@lycee.fr',
    role: 'stagiaire',
    nom: 'Dubois',
    prenom: 'Camille',
    ecole: 'Lycée Victor Duruy',
    specialite: 'Terminale - Spécialité NSI',
    telephone: '06 56 78 90 12',
    ecoleId: 'ecole-1',
    createdAt: '2024-02-11',
  },
  {
    id: 'stg-ecole-3',
    email: 'lucas.marchand@lycee.fr',
    role: 'stagiaire',
    nom: 'Marchand',
    prenom: 'Lucas',
    ecole: 'Lycée Victor Duruy',
    specialite: 'Terminale - Spécialité NSI',
    telephone: '06 67 89 01 23',
    ecoleId: 'ecole-1',
    createdAt: '2024-02-12',
  },
  {
    id: 'stg-ecole-4',
    email: 'valentin.moreau@college.fr',
    role: 'stagiaire',
    nom: 'Moreau',
    prenom: 'Valentin',
    ecole: 'Collège Jean Jaurès',
    specialite: '3ème - Découverte Professionnelle',
    telephone: '06 78 90 12 34',
    ecoleId: 'ecole-2',
    createdAt: '2024-02-13',
  },
  {
    id: 'stg-ecole-5',
    email: 'alice.lefevre@college.fr',
    role: 'stagiaire',
    nom: 'Lefevre',
    prenom: 'Alice',
    ecole: 'Collège Jean Jaurès',
    specialite: '3ème - Découverte Professionnelle',
    telephone: '06 89 01 23 45',
    ecoleId: 'ecole-2',
    createdAt: '2024-02-14',
  },
]

export const mockTuteurs: Tuteur[] = [
  {
    id: 'tut-1',
    email: 'philippe.moreau@rif.fr',
    role: 'tuteur',
    nom: 'Moreau',
    prenom: 'Philippe',
    departement: 'Informatique',
    poste: 'Chef de projet',
    stagiairesIds: ['stg-1'],
    createdAt: '2023-06-01',
  },
  {
    id: 'tut-2',
    email: 'claire.durand@rif.fr',
    role: 'tuteur',
    nom: 'Durand',
    prenom: 'Claire',
    departement: 'Marketing',
    poste: 'Responsable Marketing Digital',
    stagiairesIds: ['stg-2'],
    createdAt: '2023-08-15',
  },
]

export const mockRH: RH[] = [
  {
    id: 'rh-1',
    email: 'admin.rh@rif.fr',
    role: 'rh',
    nom: 'Lambert',
    prenom: 'Isabelle',
    createdAt: '2022-01-01',
  },
]

export const mockAdmins: Admin[] = [
  {
    id: 'admin-1',
    email: 'admin@rif.fr',
    role: 'admin',
    nom: 'Administrateur',
    prenom: 'Système',
    createdAt: '2021-01-01',
  },
]

// Universités
export const mockUniversites: Universite[] = [
  {
    id: 'univ-1',
    email: 'pierre.dubois@univ-bordeaux.fr',
    role: 'universite',
    nom: 'Dubois',
    prenom: 'Pierre',
    nomUniversite: 'Université de Bordeaux',
    telephone: '05 40 00 00 00',
    createdAt: '2025-02-05',
  },
  {
    id: 'univ-2',
    email: 'contact@esprit.tn',
    role: 'universite',
    nom: 'Ben Ali',
    prenom: 'Fatima',
    nomUniversite: 'ESPRIT',
    telephone: '21 671 234 567',
    createdAt: '2025-02-06',
  },
  {
    id: 'univ-3',
    email: 'responsable@isetn.tn',
    role: 'universite',
    nom: 'Kammoun',
    prenom: 'Mohamed',
    nomUniversite: 'ISETN - Institut Supérieur d\'Études Technologiques de Nabeul',
    telephone: '21 286 123 456',
    createdAt: '2025-02-06',
  },
  {
    id: 'univ-4',
    email: 'contact@uvt.tn',
    role: 'universite',
    nom: 'Mbarek',
    prenom: 'Aïcha',
    nomUniversite: 'Université Virtuelle de Tunis',
    telephone: '21 562 789 012',
    createdAt: '2025-02-06',
  },
]

// Écoles
export const mockEcoles: Ecole[] = [
  {
    id: 'ecole-1',
    email: 'contact@lycee-victor-duruy.fr',
    role: 'ecole',
    nom: 'Duruy',
    prenom: 'Direction',
    nomEcole: 'Lycée Victor Duruy',
    niveau: 'lycee',
    telephone: '05 57 92 38 28',
    adresse: '15 Place de la Comédie',
    ville: 'Bordeaux',
    createdAt: '2025-02-10',
  },
  {
    id: 'ecole-2',
    email: 'contact@college-jaures.fr',
    role: 'ecole',
    nom: 'Gautier',
    prenom: 'Direction',
    nomEcole: 'Collège Jean Jaurès',
    niveau: 'college',
    telephone: '05 56 81 55 25',
    adresse: '28 Rue Dieudonné Costes',
    ville: 'Bordeaux',
    createdAt: '2025-02-10',
  },
  {
    id: 'ecole-3',
    email: 'contact@bts-audiovisuel.fr',
    role: 'ecole',
    nom: 'Bernard',
    prenom: 'Direction',
    nomEcole: 'BTS Audiovisuel',
    niveau: 'bts',
    telephone: '05 56 44 58 10',
    adresse: '45 Rue Mably',
    ville: 'Bordeaux',
    createdAt: '2025-02-10',
  },
]

// Demandes de partenariat
export const mockDemandesPartenariat: DemandePartenariat[] = [
  {
    id: 'dem-part-1',
    nomUniversite: 'Université de Bordeaux',
    responsableNom: 'Dubois',
    responsablePrenom: 'Pierre',
    responsableEmail: 'pierre.dubois@univ-bordeaux.fr',
    responsableTelephone: '05 40 00 00 00',
    dateSoumission: '2025-02-01',
    status: 'nouvelle',
  },
  {
    id: 'dem-part-2',
    nomUniversite: 'ENSEIRB-MATMECA',
    responsableNom: 'Martin',
    responsablePrenom: 'Sophie',
    responsableEmail: 'sophie.martin@enseirb.fr',
    responsableTelephone: '05 56 84 63 00',
    dateSoumission: '2025-01-25',
    status: 'en_revision',
    commentairesAdmin: 'À vérifier les coordonnées',
  },
]

// Candidatures
export const mockCandidatures: Candidature[] = [
  {
    id: 'cand-1',
    stagiaireId: 'stg-1',
    status: 'acceptee',
    dateSoumission: '2024-01-16',
    cvUrl: '/documents/cv-marie-dupont.pdf',
    informationsPersonnelles: {
      dateNaissance: '2001-05-15',
      adresse: '12 rue des Lilas',
      ville: 'Bordeaux',
      codePostal: '33000',
    },
    formation: {
      ecole: 'ENSEIRB-MATMECA',
      niveau: 'Bac+5',
      specialite: 'Informatique',
      annee: '2024',
    },
    preferencesStage: {
      dateDebut: '2024-03-01',
      dateFin: '2024-08-31',
      departementSouhaite: 'Informatique',
      sujetSouhaite: 'Développement Web Full Stack',
      motivation: 'Passionnée par le développement web, je souhaite mettre en pratique mes compétences acquises durant ma formation.',
    },
    commentairesRH: 'Excellent profil, compétences techniques solides.',
    dateDecision: '2024-01-20',
  },
  {
    id: 'cand-2',
    stagiaireId: 'stg-2',
    status: 'acceptee',
    dateSoumission: '2024-01-21',
    cvUrl: '/documents/cv-jean-martin.pdf',
    informationsPersonnelles: {
      dateNaissance: '2000-08-22',
      adresse: '45 avenue de la République',
      ville: 'Pessac',
      codePostal: '33600',
    },
    formation: {
      ecole: 'Université de Bordeaux',
      niveau: 'Bac+4',
      specialite: 'Marketing',
      annee: '2024',
    },
    preferencesStage: {
      dateDebut: '2024-02-15',
      dateFin: '2024-07-15',
      departementSouhaite: 'Marketing',
      sujetSouhaite: 'Marketing Digital et SEO',
      motivation: 'Je souhaite développer mes compétences en marketing digital au sein d\'une grande entreprise.',
    },
    commentairesRH: 'Bon profil, motivé.',
    dateDecision: '2024-01-25',
  },
  {
    id: 'cand-3',
    stagiaireId: 'stg-3',
    status: 'soumise',
    dateSoumission: '2024-02-02',
    cvUrl: '/documents/cv-sophie-bernard.pdf',
    informationsPersonnelles: {
      dateNaissance: '2001-12-03',
      adresse: '8 place Gambetta',
      ville: 'Bordeaux',
      codePostal: '33000',
    },
    formation: {
      ecole: 'Sciences Po Bordeaux',
      niveau: 'Bac+5',
      specialite: 'Communication',
      annee: '2024',
    },
    preferencesStage: {
      dateDebut: '2024-04-01',
      dateFin: '2024-09-30',
      departementSouhaite: 'Communication',
      sujetSouhaite: 'Communication Institutionnelle',
      motivation: 'Je souhaite contribuer à la stratégie de communication du groupe RIF.',
    },
    commentairesRH: null,
    dateDecision: null,
    analyseCV: {
      score: 82,
      competences: ['JavaScript', 'React', 'Node.js', 'SQL', 'Communication'],
      experience: 'Intermédiaire',
      formation: 'Bac+3 (Licence)',
      points_forts: ['Bonnes compétences techniques', 'Expérience en gestion de projet', 'Communication développée'],
      points_amelioration: ['Approfondir les compétences backend', 'Développer expérience en Cloud'],
      resume: 'Candidat(e) présentant 5 compétences identifiées. Niveau Intermédiaire. Formation: Bac+3 (Licence)',
      date_analyse: '2025-02-05',
    },
  },
  {
    id: 'cand-2',
    stagiaireId: 'stg-2',
    status: 'en_revision',
    dateSoumission: '2024-02-01',
    cvUrl: '/documents/cv-lucas-chen.pdf',
    informationsPersonnelles: {
      dateNaissance: '2001-03-22',
      adresse: '45 avenue Thiers',
      ville: 'Bordeaux',
      codePostal: '33100',
    },
    formation: {
      ecole: 'ENSEIRB-MATMECA',
      niveau: 'Bac+5',
      specialite: 'Informatique - Systèmes et Réseaux',
      annee: '2024',
    },
    preferencesStage: {
      dateDebut: '2024-03-15',
      dateFin: '2024-08-15',
      departementSouhaite: 'Informatique',
      sujetSouhaite: 'Sécurité informatique et Réseaux',
      motivation: 'Intéressé par les défis de sécurité et l\'infrastructure réseau.',
    },
    commentairesRH: null,
    dateDecision: null,
    analyseCV: {
      score: 88,
      competences: ['Python', 'Java', 'SQL', 'Sécurité informatique', 'Linux', 'Management'],
      experience: 'Intermédiaire',
      formation: 'Bac+5 (Master)',
      points_forts: ['Niveau d\'études élevé (Master)', 'Compétences techniques solides', 'Expérience professionnelle démontrée'],
      points_amelioration: ['Renforcer les compétences en Cloud', 'Démontrer plus de projects'],
      resume: 'Candidat(e) présentant 6 compétences identifiées. Niveau Intermédiaire. Formation: Bac+5 (Master)',
      date_analyse: '2025-02-04',
    },
  },
  {
    id: 'cand-3',
    stagiaireId: 'stg-3',
    status: 'soumise',
    dateSoumission: '2024-02-02',
    cvUrl: '/documents/cv-sophie-bernard.pdf',
    informationsPersonnelles: {
      dateNaissance: '2001-12-03',
      adresse: '8 place Gambetta',
      ville: 'Bordeaux',
      codePostal: '33000',
    },
    formation: {
      ecole: 'Sciences Po Bordeaux',
      niveau: 'Bac+5',
      specialite: 'Communication',
      annee: '2024',
    },
    preferencesStage: {
      dateDebut: '2024-04-01',
      dateFin: '2024-09-30',
      departementSouhaite: 'Communication',
      sujetSouhaite: 'Communication Institutionnelle',
      motivation: 'Je souhaite contribuer à la stratégie de communication du groupe RIF.',
    },
    commentairesRH: null,
    dateDecision: null,
    analyseCV: {
      score: 65,
      competences: ['Communication', 'Travail en équipe', 'Créativité', 'Gestion de projets'],
      experience: 'Débutant avec expérience',
      formation: 'Bac+5 (Master)',
      points_forts: ['Niveau d\'études élevé (Master)', 'Compétences en communication solides'],
      points_amelioration: ['Enrichir l\'expérience professionnelle', 'Développer davantage les compétences techniques', 'Inclure un portfolio'],
      resume: 'Candidat(e) présentant 4 compétences identifiées. Niveau Débutant avec expérience. Formation: Bac+5 (Master)',
      date_analyse: '2025-02-02',
    },
  },
]

// Conventions
export const mockConventions: Convention[] = [
  {
    id: 'conv-1',
    candidatureId: 'cand-1',
    stagiaireId: 'stg-1',
    status: 'signee_complete',
    dateGeneration: '2024-01-21',
    dateSignature: '2024-01-28',
    contenu: {
      dateDebut: '2024-03-01',
      dateFin: '2024-08-31',
      departement: 'Informatique',
      tuteurNom: 'Philippe Moreau',
      sujet: 'Développement Web Full Stack',
    },
  },
  {
    id: 'conv-2',
    candidatureId: 'cand-2',
    stagiaireId: 'stg-2',
    status: 'signee_complete',
    dateGeneration: '2024-01-26',
    dateSignature: '2024-02-05',
    contenu: {
      dateDebut: '2024-02-15',
      dateFin: '2024-07-15',
      departement: 'Marketing',
      tuteurNom: 'Claire Durand',
      sujet: 'Marketing Digital et SEO',
    },
  },
]

// Tâches Onboarding
export const mockTachesOnboarding: TacheOnboarding[] = [
  // For stg-1
  { id: 'tache-1', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Accueil et présentation de l\'équipe', status: 'termine', echeance: '2024-03-01', notes: 'Fait le premier jour', ordre: 1 },
  { id: 'tache-2', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Configuration des accès systèmes', status: 'termine', echeance: '2024-03-01', notes: null, ordre: 2 },
  { id: 'tache-3', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Visite des locaux', status: 'termine', echeance: '2024-03-01', notes: null, ordre: 3 },
  { id: 'tache-4', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Présentation du projet/mission', status: 'termine', echeance: '2024-03-02', notes: null, ordre: 4 },
  { id: 'tache-5', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Définition des objectifs du stage', status: 'en_cours', echeance: '2024-03-05', notes: 'En discussion', ordre: 5 },
  { id: 'tache-6', tuteurId: 'tut-1', stagiaireId: 'stg-1', description: 'Formation aux règles de sécurité', status: 'a_faire', echeance: '2024-03-08', notes: null, ordre: 6 },
  // For stg-2
  { id: 'tache-7', tuteurId: 'tut-2', stagiaireId: 'stg-2', description: 'Accueil et présentation de l\'équipe', status: 'termine', echeance: '2024-02-15', notes: null, ordre: 1 },
  { id: 'tache-8', tuteurId: 'tut-2', stagiaireId: 'stg-2', description: 'Configuration des accès systèmes', status: 'termine', echeance: '2024-02-15', notes: null, ordre: 2 },
  { id: 'tache-9', tuteurId: 'tut-2', stagiaireId: 'stg-2', description: 'Visite des locaux', status: 'termine', echeance: '2024-02-15', notes: null, ordre: 3 },
  { id: 'tache-10', tuteurId: 'tut-2', stagiaireId: 'stg-2', description: 'Présentation du projet/mission', status: 'termine', echeance: '2024-02-16', notes: null, ordre: 4 },
  { id: 'tache-11', tuteurId: 'tut-2', stagiaireId: 'stg-2', description: 'Définition des objectifs du stage', status: 'termine', echeance: '2024-02-20', notes: null, ordre: 5 },
]

// Evaluations
export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval-1',
    stagiaireId: 'stg-2',
    tuteurId: 'tut-2',
    competencesTechniques: 4,
    autonomie: 4,
    integrationEquipe: 5,
    commentaires: 'Jean a fait preuve d\'une excellente intégration au sein de l\'équipe. Ses compétences techniques sont solides et il a su être autonome rapidement.',
    date: '2024-07-10',
    certificatGenere: true,
  },
]

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'rh-1',
    type: 'candidature',
    contenu: 'Nouvelle candidature de Sophie Bernard',
    lu: false,
    date: '2024-02-02',
    lien: '/rh/candidatures/cand-3',
  },
  {
    id: 'notif-2',
    userId: 'tut-1',
    type: 'onboarding',
    contenu: 'Rappel: Tâches d\'onboarding à compléter pour Marie Dupont',
    lu: false,
    date: '2024-03-03',
    lien: '/tuteur/onboarding/stg-1',
  },
  {
    id: 'notif-3',
    userId: 'stg-1',
    type: 'convention',
    contenu: 'Votre convention a été générée',
    lu: true,
    date: '2024-01-21',
    lien: '/stagiaire/convention',
  },
]

// Helper to get all users
export function getAllUsers(): User[] {
  return [
    ...mockStagiaires,
    ...mockTuteurs,
    ...mockRH,
    ...mockAdmins,
    ...mockUniversites,
    ...mockEcoles,
  ]
}

// Candidatures externes (formulaire public)
export const mockCandidaturesExternes: CandidatureExterne[] = [
  {
    id: 'cand-ext-1',
    nom: 'Leroy',
    prenom: 'Alice',
    email: 'alice.leroy@univ-bordeaux.fr',
    telephone: '06 45 67 89 01',
    adresse: '25 rue de la Liberté',
    ville: 'Bordeaux',
    codePostal: '33000',
    formation: 'Master Informatique',
    niveau: 'bac+5',
    dateDebut: '2024-04-01',
    duree: '4-6',
    message: 'Je suis passionnée par le développement logiciel et souhaite rejoindre une équipe dynamique pour mettre en pratique mes connaissances.',
    cvUrl: '/documents/cv-alice-leroy.pdf',
    lettreMotivationUrl: '/documents/lm-alice-leroy.pdf',
    status: 'nouvelle',
    dateSoumission: '2024-02-10',
  },
  {
    id: 'cand-ext-2',
    nom: 'Petit',
    prenom: 'Lucas',
    email: 'lucas.petit@iae-bordeaux.fr',
    telephone: '06 78 90 12 34',
    adresse: '8 avenue Jean Jaurès',
    ville: 'Talence',
    codePostal: '33400',
    formation: 'Master Marketing Digital',
    niveau: 'bac+5',
    dateDebut: '2024-05-01',
    duree: '2-4',
    message: 'Fort de mes expériences en marketing digital, je souhaite contribuer à la stratégie digitale du groupe RIF.',
    cvUrl: '/documents/cv-lucas-petit.pdf',
    lettreMotivationUrl: '/documents/lm-lucas-petit.pdf',
    status: 'nouvelle',
    dateSoumission: '2024-02-08',
  },
  {
    id: 'cand-ext-3',
    nom: 'Moreau',
    prenom: 'Emma',
    email: 'emma.moreau@sciencespo-bordeaux.fr',
    telephone: '06 23 45 67 89',
    adresse: '15 cours de l\'Intendance',
    ville: 'Bordeaux',
    codePostal: '33000',
    formation: 'Master Communication',
    niveau: 'bac+5',
    dateDebut: '2024-03-15',
    duree: '4-6',
    message: 'Passionnée par la communication institutionnelle, je souhaite mettre mes compétences au service de votre groupe.',
    cvUrl: '/documents/cv-emma-moreau.pdf',
    lettreMotivationUrl: '/documents/lm-emma-moreau.pdf',
    status: 'en_revision',
    dateSoumission: '2024-02-05',
    commentairesRH: 'Profil intéressant, à revoir pour le département Communication.',
  },
  {
    id: 'cand-ext-4',
    nom: 'Dubois',
    prenom: 'Thomas',
    email: 'thomas.dubois@enseirb.fr',
    telephone: '06 12 34 56 78',
    adresse: '42 rue des Sciences',
    ville: 'Pessac',
    codePostal: '33600',
    formation: 'Ingénieur Informatique',
    niveau: 'bac+5',
    dateDebut: '2024-03-01',
    duree: '4-6',
    message: 'Développeur full-stack passionné, je recherche un stage de fin d\'études pour mettre en pratique mes compétences.',
    cvUrl: '/documents/cv-thomas-dubois.pdf',
    lettreMotivationUrl: '/documents/lm-thomas-dubois.pdf',
    status: 'acceptee',
    dateSoumission: '2024-01-25',
    departementAffecte: 'Informatique',
    commentairesRH: 'Excellent profil technique. A intégrer dans l\'équipe dev.',
    dateDecision: '2024-02-01',
  },
  {
    id: 'cand-ext-5',
    nom: 'Garcia',
    prenom: 'Julie',
    email: 'julie.garcia@univ-bordeaux.fr',
    telephone: '06 98 76 54 32',
    adresse: '3 place de la Victoire',
    ville: 'Bordeaux',
    codePostal: '33000',
    formation: 'Master Finance',
    niveau: 'bac+5',
    dateDebut: '2024-04-15',
    duree: '4-6',
    message: 'Je souhaite mettre mes compétences en analyse financière au service de votre département finance.',
    cvUrl: '/documents/cv-julie-garcia.pdf',
    lettreMotivationUrl: '/documents/lm-julie-garcia.pdf',
    status: 'acceptee',
    dateSoumission: '2024-01-20',
    departementAffecte: 'Finance',
    commentairesRH: 'Très bon profil, compétences analytiques solides.',
    dateDecision: '2024-01-28',
  },
  {
    id: 'cand-ext-6',
    nom: 'Roux',
    prenom: 'Maxime',
    email: 'maxime.roux@iut-bordeaux.fr',
    telephone: '06 11 22 33 44',
    formation: 'DUT Informatique',
    niveau: 'bac+2',
    dateDebut: '2024-05-01',
    duree: '1-2',
    cvUrl: '/documents/cv-maxime-roux.pdf',
    lettreMotivationUrl: '/documents/lm-maxime-roux.pdf',
    status: 'refusee',
    dateSoumission: '2024-01-15',
    commentairesRH: 'Profil ne correspondant pas aux besoins actuels.',
    dateDecision: '2024-01-22',
  },
]

// Mock credentials for demo
export const mockCredentials = [
  { email: 'marie.dupont@edu.fr', password: 'demo123', role: 'stagiaire' as const },
  { email: 'philippe.moreau@rif.fr', password: 'demo123', role: 'tuteur' as const },
  { email: 'admin.rh@rif.fr', password: 'demo123', role: 'rh' as const },
  { email: 'admin@rif.fr', password: 'demo123', role: 'admin' as const },
  { email: 'pierre.dubois@univ-bordeaux.fr', password: 'TempPass123!', role: 'universite' as const },
  { email: 'contact@esprit.tn', password: 'ESPRIT2024!', role: 'universite' as const },
  { email: 'responsable@isetn.tn', password: 'ISETN2024!', role: 'universite' as const },
  { email: 'contact@uvt.tn', password: 'UVT2024!', role: 'universite' as const },
  { email: 'contact@lycee-victor-duruy.fr', password: 'LyceeVD2024!', role: 'ecole' as const },
  { email: 'contact@college-jaures.fr', password: 'CollegeJJ2024!', role: 'ecole' as const },
  { email: 'contact@bts-audiovisuel.fr', password: 'BTS2024!', role: 'ecole' as const },
]
